<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-Q23M30KF" failures="1" tests="6" name="test.kienlhpc05751.TaoVourcher1" time="24.092" errors="0" timestamp="2024-04-14T15:17:00 ICT" skipped="0">
  <testcase classname="test.kienlhpc05751.TaoVourcher1" name="TC_QLCF_QLVOUCHER_01" time="3.097"/>
  <system-out/>
  <testcase classname="test.kienlhpc05751.TaoVourcher1" name="TC_QLCF_QLVOUCHER_06" time="1.689">
    <failure message="expected [Giá trị chưa đúng] but found [Giá trị voucher từ 10-500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Giá trị chưa đúng] but found [Giá trị voucher từ 10-500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at test.kienlhpc05751.TaoVourcher1.TC_QLCF_QLVOUCHER_06(TaoVourcher1.java:115)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_QLCF_QLVOUCHER_06 -->
  <system-out/>
  <testcase classname="test.kienlhpc05751.TaoVourcher1" name="TC_QLCF_QLVOUCHER_03" time="0.948"/>
  <system-out/>
  <testcase classname="test.kienlhpc05751.TaoVourcher1" name="TC_QLCF_QLVOUCHER_05" time="16.664"/>
  <system-out/>
  <testcase classname="test.kienlhpc05751.TaoVourcher1" name="TC_QLCF_QLVOUCHER_02" time="0.790"/>
  <system-out/>
  <testcase classname="test.kienlhpc05751.TaoVourcher1" name="TC_QLCF_QLVOUCHER_04" time="0.904"/>
  <system-out/>
</testsuite> <!-- test.kienlhpc05751.TaoVourcher1 -->
